# Generated by Django 3.2 on 2021-05-17 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demouser',
            fields=[
                ('uId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('time_duration', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('no_of_openings', models.IntegerField()),
                ('skills', models.CharField(default='', max_length=500)),
                ('required', models.CharField(default='', max_length=500)),
                ('start_date', models.DateField()),
                ('stipend', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='user_image/profile_pic.png', upload_to='user_image')),
                ('skills', models.CharField(max_length=500)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job')], max_length=50)),
                ('profile', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('currently_working', models.BooleanField(default=False)),
                ('userProfile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Internship.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('percentage', models.IntegerField()),
                ('stream', models.CharField(max_length=50)),
                ('userProfile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Internship.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyDate', models.DateField(default=django.utils.timezone.now)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship.internship')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship.userprofile')),
            ],
        ),
    ]
