# Generated by Django 3.2 on 2021-05-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userId',
        ),
    ]
