# Generated by Django 3.2 on 2021-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0003_userprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
