# Generated by Django 3.2 on 2021-05-21 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0004_alter_userprofile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='postedDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 21, 8, 57, 15, 973432, tzinfo=utc)),
        ),
    ]
