# Generated by Django 3.2 on 2021-05-21 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0005_internship_posteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='postedDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 21, 8, 59, 44, 163659, tzinfo=utc)),
        ),
    ]
