# Generated by Django 3.2 on 2021-05-21 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0006_alter_internship_posteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='postedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
