# Generated by Django 3.2 on 2021-07-05 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0008_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='app',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Internship.application'),
        ),
        migrations.AddField(
            model_name='demo',
            name='text',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='demo',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2021, 7, 5)),
        ),
    ]
