# Generated by Django 3.2 on 2021-07-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0009_auto_20210705_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='date',
        ),
    ]
