# Generated by Django 3.2 on 2021-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0011_demo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='image',
            field=models.ImageField(default='user_image/profile_pic.png', upload_to='user_image'),
        ),
    ]
