# Generated by Django 3.2 on 2021-07-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0012_demo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='image',
            field=models.ImageField(default='profile_pic.png', upload_to='user_image'),
        ),
    ]
