# Generated by Django 3.2 on 2021-07-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0014_alter_demo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='image',
            field=models.ImageField(default='user_image/profile_pic.png', upload_to='user_image'),
        ),
    ]
