# Generated by Django 3.2 on 2021-07-24 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0015_alter_demo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
